name: Build and Publish Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cython

    - name: Build wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload wheels to artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}  # Upload with specific OS name
        path: dist/*.whl  # Upload only .whl files

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download macOS wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels-macos-latest
        path: ./dist

    - name: Download Windows wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels-windows-latest
        path: ./dist

    - name: Download Ubuntu wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels-ubuntu-latest
        path: ./dist

    - name: Filter only .whl files
      run: |
        find ./dist -type f ! -name '*.whl' -delete  # Delete all non-.whl files

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.PYPI_API_TOKEN_FIND_KEYWORD }}
        packages_dir: ./dist  # Ensure only .whl files are in this directory
