publish:
  needs: build
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Download macOS wheels
    uses: actions/download-artifact@v3
    with:
      name: wheels-macos-latest
      path: ./dist

  - name: Download Windows wheels
    uses: actions/download-artifact@v3
    with:
      name: wheels-windows-latest
      path: ./dist

  - name: Download Ubuntu wheels
    uses: actions/download-artifact@v3
    with:
      name: wheels-ubuntu-latest
      path: ./dist

  - name: Upload to PyPI
    uses: pypa/gh-action-pypi-publish@v1.4.2
    with:
      password: ${{ secrets.PYPI_API_TOKEN_FIND_KEYWORD }}
      packages_dir: ./dist
